### ISSUE TITLE
Correct but specific searches do not yield results.  

### ISSUE THREAD

**Issue by I-graham** [blukat29/search-libc#3]
Correct searches, such as this one (https://libc.nullbyte.cat/?q=gets%3A11b0%2Cprintf%3A4340%2Crand%3A9500%2Cwrite%3A5ca0%2C__libc_start_main%3Aedf0), which includes only function addresses matching libc6_2.31-0ubuntu9.2_i386 (https://libc.nullbyte.cat/d/libc6_2.31-0ubuntu9.2_i386.symbols) do not find any results, however, after removing __libc_start_main from the query, it does return results, even though the address used in the query was extracted from libc6_2.31-0ubuntu9.2_i386.

**Comment by blukat29** [comment]
@I-graham Thanks for the report but I do not own the site. So please ask the admin there.
I am only hosting the source code in GitHub and my website [libc.blukat.me](https://libc.blukat.me).
I will however look into the case you've reported.

**Comment by I-graham** [comment]
My apologies, I was using libc.nullbyte.cat (which appears to be a clone of libc.blukat.me) while this website was down for a few days, but a very similar issue appears at libc.blukat.me. For example: symbols matching libc6_2.31-0ubuntu9_i386.symbols  (https://libc.blukat.me/d/libc6_2.31-0ubuntu9_i386.symbols) in this query (https://libc.blukat.me/?q=gets%3Ab0%2Cwrite%3Aae0%2C__libc_start_main%3Adf0%2Cprintf%3A340%2Crand%3A500) do not yield any results unless a correct field (such as write, in this example) is removed.

**Comment by blukat29** [comment]
I will look into it this evening. Thanks.

**Comment by blukat29** [comment]
@I-graham Sorry, there was a problem with updating the database since libc-database had some changes. Now it's fixed try it out. I appreciate your prompt response and interest.
