### ISSUE TITLE
Include web page css/js stuff in the local docker

### ISSUE THREAD

**Issue by cnSchwarzer** [blukat29/search-libc#4]
In offline competitions without Internet this docker image is unuseable because it need to download css/js from Internet.

**Comment by blukat29** [comment]
@cnSchwarzer Fixed by https://github.com/blukat29/search-libc/commit/6a955e0b78e5cb1730973c6467ee0d67bb31925f. Thanks for the suggestion.

**Comment by cnSchwarzer** [comment]
Thank you ❤
